import type { Mezzo } from "@/types/mobilita";

// Catalogo iniziale persistito nel database: mantiene gli stessi nomi, codici
// e valori gia consolidati nei mock storici, cosi la migrazione non cambia il
// comportamento funzionale atteso dalle UI e dai test gia svolti.
export const catalogoMezziIniziale: Mezzo[] = [
  {
    id: "mezzo-001",
    codice: "EB-1001",
    tipo: "E-Bike",
    modello: "Urban Glide One",
    stato: "DISPONIBILE",
    batteria: 92,
    latitudine: 41.12198,
    longitudine: 16.87305,
    posti: 1,
    patenteRichiesta: "Nessuna",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-002",
    codice: "ES-2044",
    tipo: "E-Scooter",
    modello: "Volt Street X",
    stato: "DISPONIBILE",
    batteria: 67,
    latitudine: 41.12182,
    longitudine: 16.87322,
    posti: 1,
    patenteRichiesta: "AM",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-003",
    codice: "EC-3007",
    tipo: "E-Car",
    modello: "City Move Mini",
    stato: "DISPONIBILE",
    batteria: 54,
    latitudine: 41.12194,
    longitudine: 16.87316,
    posti: 4,
    patenteRichiesta: "B",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-004",
    codice: "ES-2051",
    tipo: "E-Scooter",
    modello: "Volt Street X",
    stato: "DISPONIBILE",
    batteria: 43,
    latitudine: 41.1187,
    longitudine: 16.8709,
    posti: 1,
    patenteRichiesta: "AM",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-005",
    codice: "EB-1026",
    tipo: "E-Bike",
    modello: "Urban Glide Plus",
    stato: "DISPONIBILE",
    batteria: 81,
    latitudine: 41.1169,
    longitudine: 16.8759,
    posti: 1,
    patenteRichiesta: "Nessuna",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-006",
    codice: "EC-3014",
    tipo: "E-Car",
    modello: "Eco Drive Compact",
    stato: "DISPONIBILE",
    batteria: 74,
    latitudine: 41.1089,
    longitudine: 16.8786,
    posti: 2,
    patenteRichiesta: "B",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-007",
    codice: "EB-1034",
    tipo: "E-Bike",
    modello: "Urban Glide Lite",
    stato: "DISPONIBILE",
    batteria: 88,
    latitudine: 41.1256,
    longitudine: 16.8708,
    posti: 1,
    patenteRichiesta: "Nessuna",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-008",
    codice: "ES-2062",
    tipo: "E-Scooter",
    modello: "Volt Street Pro",
    stato: "DISPONIBILE",
    batteria: 58,
    latitudine: 41.1234,
    longitudine: 16.8677,
    posti: 1,
    patenteRichiesta: "AM",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-009",
    codice: "EC-3021",
    tipo: "E-Car",
    modello: "City Move Mini",
    stato: "DISPONIBILE",
    batteria: 63,
    latitudine: 41.1124,
    longitudine: 16.8661,
    posti: 4,
    patenteRichiesta: "B",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-010",
    codice: "EB-1047",
    tipo: "E-Bike",
    modello: "Urban Glide Tour",
    stato: "DISPONIBILE",
    batteria: 77,
    latitudine: 41.1049,
    longitudine: 16.8711,
    posti: 1,
    patenteRichiesta: "Nessuna",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-012",
    codice: "EC-3030",
    tipo: "E-Car",
    modello: "Eco Drive Compact",
    stato: "IN_USO",
    batteria: 46,
    latitudine: 41.1191,
    longitudine: 16.8844,
    posti: 2,
    patenteRichiesta: "B",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-013",
    codice: "EB-1058",
    tipo: "E-Bike",
    modello: "Urban Glide Plus",
    stato: "IN_MANUTENZIONE",
    batteria: 19,
    latitudine: 41.1117,
    longitudine: 16.8578,
    posti: 1,
    patenteRichiesta: "Nessuna",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-014",
    codice: "ES-2084",
    tipo: "E-Scooter",
    modello: "Volt Street Pro",
    stato: "IN_PAUSA",
    batteria: 34,
    latitudine: 41.1086,
    longitudine: 16.8892,
    posti: 1,
    patenteRichiesta: "AM",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-015",
    codice: "EC-3042",
    tipo: "E-Car",
    modello: "Eco Drive Urban",
    stato: "NON_DISPONIBILE",
    batteria: 11,
    latitudine: 41.0988,
    longitudine: 16.8682,
    posti: 2,
    patenteRichiesta: "B",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
  {
    id: "mezzo-016",
    codice: "ES-2091",
    tipo: "E-Scooter",
    modello: "Volt Street Lite",
    stato: "DISPONIBILE",
    batteria: 71,
    latitudine: 41.12212,
    longitudine: 16.87336,
    posti: 1,
    patenteRichiesta: "AM",
    areaServizioId: "area-bari-urbana",
    areaServizioNome: "Area urbana di Bari",
  },
];
